# Project 2: Data Import - Working with Web APIs and JSON (Movies Dataset)

In [11]:
import pandas as pd

In [12]:
import json

In [22]:
df = pd.read_json('blockbusters.json')

In [4]:
df

,title,id,revenue,genres,belongs_to_collection,runtime
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",124
6,The Lion King,420818,1656943394,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",None,118
7,The Avengers,24428,1519557910,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","{'id': 86311, 'name': 'The Avengers Collection...",143
8,Furious 7,168259,1506249360,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...","{'id': 9485, 'name': 'The Fast and the Furious...",137
9,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 86311, 'name': 'The Avengers Collection...",141
10,Black Panther,284054,1346739107,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 529892, 'name': 'Black Panther Collecti...",134
11,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...","{'id': 1241, 'name': 'Harry Potter Collection'...",130
12,Star Wars: The Last Jedi,181808,1332539889,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...","{'id': 10, 'name': 'Star Wars Collection', 'po...",152
13,Frozen II,330457,1330764959,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","{'id': 386382, 'name': 'Frozen Collection', 'p...",104
14,Jurassic World: Fallen Kingdom,351286,1303459585,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",129
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...","{'id': 386382, 'name': 'Frozen Collection', 'p...",102
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",None,129
17,Incredibles 2,260513,1241891456,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 468222, 'name': 'The Incredibles Collec...",118

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  18 non-null     object
 1   id                     18 non-null     int64
 2   revenue                18 non-null     int64
 3   genres                 18 non-null     object
 4   belongs_to_collection  15 non-null     object
 5   runtime                18 non-null     int64
dtypes: int64(3), object(3)
memory usage: 996.0+ bytes

In [6]:
len(df)

18

In [17]:
df.genres[0]

[{'id': 12, 'name': 'Adventure'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 28, 'name': 'Action'}]

In [18]:
df.belongs_to_collection[0]

{'id': 86311,
 'name': 'The Avengers Collection',
 'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
 'backdrop_path': '/zuW6fOiusv4X9nnW3paHGfXcSll.jpg'}

In [24]:
with open('blockbusters.json') as f:
    data = json.load(f)

In [25]:
pd.json_normalize(data = data, sep = "_")

,title,id,revenue,genres,runtime,belongs_to_collection_id,belongs_to_collection_name,belongs_to_collection_poster_path,belongs_to_collection_backdrop_path,belongs_to_collection
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",181,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
1,Avatar,19995,2787965087,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",162,87096.0,Avatar Collection,/nslJVsO58Etqkk17oXMuVK4gNOF.jpg,/8nCr9W7sKus2q9PLbYsnT7iCkuT.jpg,NaN
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",136,10.0,Star Wars Collection,/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",149,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
4,Titanic,597,1845034188,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",194,NaN,NaN,NaN,NaN,NaN
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",124,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg,NaN
6,The Lion King,420818,1656943394,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",118,NaN,NaN,NaN,NaN,NaN
7,The Avengers,24428,1519557910,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",143,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
8,Furious 7,168259,1506249360,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",137,9485.0,The Fast and the Furious Collection,/uv63yAGg1zETAs1XQsOQpava87l.jpg,/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg,NaN
9,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
10,Black Panther,284054,1346739107,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",134,529892.0,Black Panther Collection,/9ZSPIsxI3TZDgfg0Jzk0RZl4INg.jpg,/1Jj7Frjjbewb6Q6dl6YXhL3kuvL.jpg,NaN
11,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",130,1241.0,Harry Potter Collection,/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg,/wfnMt6LGqYHcNyOfsuusw5lX3bL.jpg,NaN
12,Star Wars: The Last Jedi,181808,1332539889,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",152,10.0,Star Wars Collection,/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
13,Frozen II,330457,1330764959,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",104,386382.0,Frozen Collection,/rpoXnE9UzCbjmINhxIi8bZF557B.jpg,/vZiqhw6oFoMlHSneIdVip9rRou2.jpg,NaN
14,Jurassic World: Fallen Kingdom,351286,1303459585,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",129,328.0,Jurassic Park Collection,/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg,/pJjIH9QN0OkHFV9eue6XfRVnPkr.jpg,NaN
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",102,386382.0,Frozen Collection,/rpoXnE9UzCbjmINhxIi8bZF557B.jpg,/vZiqhw6oFoMlHSneIdVip9rRou2.jpg,NaN
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",129,NaN,NaN,NaN,NaN,NaN
17,Incredibles 2,260513,1241891456,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",118,468222.0,The Incredibles Collection,/l7GqbzkJwowYRIXAtUz2iCPi64a.jpg,/9eDW2dVhnzPS2HvaRdK2OlAGaLq.jpg,NaN

In [26]:
pd.json_normalize(data = data, record_path = 'genres',meta = ['title','id'],record_prefix="genre_")

,genre_id,genre_name,title,id
0,12,Adventure,Avengers: Endgame,299534
1,878,Science Fiction,Avengers: Endgame,299534
2,28,Action,Avengers: Endgame,299534
3,28,Action,Avatar,19995
4,12,Adventure,Avatar,19995
5,14,Fantasy,Avatar,19995
6,878,Science Fiction,Avatar,19995
7,28,Action,Star Wars: The Force Awakens,140607
8,12,Adventure,Star Wars: The Force Awakens,140607
9,878,Science Fiction,Star Wars: The Force Awakens,140607
10,14,Fantasy,Star Wars: The Force Awakens,140607
11,12,Adventure,Avengers: Infinity War,299536
12,28,Action,Avengers: Infinity War,299536
13,878,Science Fiction,Avengers: Infinity War,299536
14,18,Drama,Titanic,597
15,10749,Romance,Titanic,597
16,53,Thriller,Titanic,597
17,28,Action,Jurassic World,135397
18,12,Adventure,Jurassic World,135397
19,878,Science Fiction,Jurassic World,135397
20,53,Thriller,Jurassic World,135397
21,12,Adventure,The Lion King,420818
22,10751,Family,The Lion King,420818
23,878,Science Fiction,The Avengers,24428
24,28,Action,The Avengers,24428
25,12,Adventure,The Avengers,24428
26,28,Action,Furious 7,168259
27,53,Thriller,Furious 7,168259
28,28,Action,Avengers: Age of Ultron,99861
29,12,Adventure,Avengers: Age of Ultron,99861
30,878,Science Fiction,Avengers: Age of Ultron,99861
31,28,Action,Black Panther,284054
32,12,Adventure,Black Panther,284054
33,14,Fantasy,Black Panther,284054
34,878,Science Fiction,Black Panther,284054
35,14,Fantasy,Harry Potter and the Deathly Hallows: Part 2,12445
36,12,Adventure,Harry Potter and the Deathly Hallows: Part 2,12445
37,14,Fantasy,Star Wars: The Last Jedi,181808
38,12,Adventure,Star Wars: The Last Jedi,181808
39,878,Science Fiction,Star Wars: The Last Jedi,181808
40,28,Action,Star Wars: The Last Jedi,181808
41,16,Animation,Frozen II,330457
42,10751,Family,Frozen II,330457
43,12,Adventure,Frozen II,330457
44,28,Action,Jurassic World: Fallen Kingdom,351286
45,12,Adventure,Jurassic World: Fallen Kingdom,351286
46,878,Science Fiction,Jurassic World: Fallen Kingdom,351286
47,16,Animation,Frozen,109445
48,12,Adventure,Frozen,109445
49,10751,Family,Frozen,109445
50,10751,Family,Beauty and the Beast,321612
51,14,Fantasy,Beauty and the Beast,321612
52,10749,Romance,Beauty and the Beast,321612
53,28,Action,Incredibles 2,260513
54,12,Adventure,Incredibles 2,260513
55,16,Animation,Incredibles 2,260513
56,10751,Family,Incredibles 2,260513

## Working with APIs and JSON (Part 1)

In [9]:
import requests

In [1]:
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("api_key")

In [14]:
url = "https://www.omdbapi.com/"
params = {
    "apikey": api_key,
    "i": "tt3896198"
}

response = requests.get(url, params=params)

data = response.json()

df = pd.DataFrame([data])

print(df.head())

                             Title  Year  Rated     Released  Runtime  \
0  Guardians of the Galaxy: Vol. 2  2017  PG-13  05 May 2017  136 min

                       Genre    Director  \
0  Action, Adventure, Comedy  James Gunn

                                 Writer  \
0  James Gunn, Dan Abnett, Andy Lanning

                                    Actors  \
0  Chris Pratt, Zoe Saldaña, Dave Bautista

                                                Plot  ... Metascore  \
0  The Guardians struggle to keep together as a t...  ...        67

  imdbRating imdbVotes     imdbID   Type  DVD     BoxOffice Production  \
0        7.6   828,114  tt3896198  movie  N/A  $389,813,101        N/A

  Website Response
0     N/A     True

[1 rows x 25 columns]

In [15]:
url = "https://www.omdbapi.com/"
params = {
    "apikey": api_key,
    "t": "Inception"
}

response = requests.get(url, params=params)

data = response.json()

df = pd.DataFrame([data])

print(df.head())

       Title  Year  Rated     Released  Runtime                      Genre  \
0  Inception  2010  PG-13  16 Jul 2010  148 min  Action, Adventure, Sci-Fi

            Director             Writer  \
0  Christopher Nolan  Christopher Nolan

                                              Actors  \
0  Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...

                                                Plot  ... Metascore  \
0  A thief who steals corporate secrets through t...  ...        74

  imdbRating  imdbVotes     imdbID   Type  DVD     BoxOffice Production  \
0        8.8  2,811,614  tt1375666  movie  N/A  $292,587,330        N/A

  Website Response
0     N/A     True

[1 rows x 25 columns]

In [55]:
df["Title"]

0    Inception
Name: Title, dtype: object

In [56]:
df[["Title", "Year", "imdbRating"]]

       Title  Year imdbRating
0  Inception  2010        8.8

In [57]:
df.columns

Index(['Title', 'Year', 'Rated', 'Released', 'Runtime', 'Genre', 'Director',
       'Writer', 'Actors', 'Plot', 'Language', 'Country', 'Awards', 'Poster',
       'Ratings', 'Metascore', 'imdbRating', 'imdbVotes', 'imdbID', 'Type',
       'DVD', 'BoxOffice', 'Production', 'Website', 'Response'],
      dtype='object')

In [58]:
df.columns.tolist()

['Title',
 'Year',
 'Rated',
 'Released',
 'Runtime',
 'Genre',
 'Director',
 'Writer',
 'Actors',
 'Plot',
 'Language',
 'Country',
 'Awards',
 'Poster',
 'Ratings',
 'Metascore',
 'imdbRating',
 'imdbVotes',
 'imdbID',
 'Type',
 'DVD',
 'BoxOffice',
 'Production',
 'Website',
 'Response']

In [16]:
params = {
    "apikey": api_key,
    "t": "The Shawshank Redemption"
}

response = requests.get(url, params=params)

data = response.json()

df = pd.DataFrame([data])

print(df.head())

                      Title  Year Rated     Released  Runtime  Genre  \
0  The Shawshank Redemption  1994     R  14 Oct 1994  142 min  Drama

         Director                        Writer  \
0  Frank Darabont  Stephen King, Frank Darabont

                                    Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton

                                                Plot  ... Metascore  \
0  A wrongfully convicted banker forms a close fr...  ...        82

  imdbRating  imdbVotes     imdbID   Type  DVD    BoxOffice Production  \
0        9.3  3,182,645  tt0111161  movie  N/A  $28,767,189        N/A

  Website Response
0     N/A     True

[1 rows x 25 columns]

##  Importing and Saving the Movies Dataset (Best Practice)

In [18]:

movie_ids = [
    "tt1375666",
    "tt3896198",
    "tt0133093"
]

In [19]:
print(url)

https://www.omdbapi.com/

In [20]:
movies = []

In [21]:
for movie_id in movie_ids:
    params = {
        "apikey":api_key,
        "i": movie_id
    }

    data = requests.get(url,params = params).json()

    if data["Response"]=="True":
        movies.append(data)

In [68]:
df = pd.DataFrame(movies)

In [69]:
df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Inception,2010,PG-13,16 Jul 2010,148 min,"Action, Adventure, Sci-Fi",Christopher Nolan,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellio...",A thief who steals corporate secrets through t...,...,74,8.8,"2,811,614",tt1375666,movie,N/A,"$292,587,330",N/A,N/A,True
1,Guardians of the Galaxy: Vol. 2,2017,PG-13,05 May 2017,136 min,"Action, Adventure, Comedy",James Gunn,"James Gunn, Dan Abnett, Andy Lanning","Chris Pratt, Zoe Saldaña, Dave Bautista",The Guardians struggle to keep together as a t...,...,67,7.6,"828,114",tt3896198,movie,N/A,"$389,813,101",N/A,N/A,True
2,The Matrix,1999,R,31 Mar 1999,136 min,"Action, Sci-Fi","Lana Wachowski, Lilly Wachowski","Lilly Wachowski, Lana Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",When a beautiful stranger leads computer hacke...,...,73,8.7,"2,243,093",tt0133093,movie,N/A,"$177,559,005",N/A,N/A,True